var exec, ref, request, spawn;

ref = require('child_process'), spawn = ref.spawn, exec = ref.exec;

request = require('request');
window.$ = window.jQuery = require('jquery');
$( document ).ready(
  console.log('HELLO')
);
// ---
// generated by coffee-script 1.9.2